### ISSUE TITLE
Error with MPLight

### ISSUE THREAD

**Issue by thoithoi58** [DaRL-LibSignal/LibSignal#2]
I got this error when running MPLight algo, no problem with FRAP btw. Please take a look, thanks
```Traceback (most recent call last):
  File "/home/ubuntu/LibSignal/run.py", line 72, in <module>
    test.run()
  File "/home/ubuntu/LibSignal/run.py", line 66, in run
    self.task.run()
  File "/home/ubuntu/LibSignal/task/task.py", line 30, in run
    self.trainer.train()
  File "/home/ubuntu/LibSignal/trainer/tsc_trainer.py", line 131, in train
    obs, rewards, dones, _ = self.env.step(actions.flatten())
  File "/home/ubuntu/LibSignal/environment.py", line 44, in step
    self.world.step(actions)
  File "/home/ubuntu/LibSignal/world/world_cityflow.py", line 518, in step
    self.intersections[i].step(action, self.interval)
  File "/home/ubuntu/LibSignal/world/world_cityflow.py", line 121, in step
    self._change_phase(self.phases[self.action_before_yellow], interval,'add')
TypeError: list indices must be integers or slices, not NoneType```

**Comment by ShawLen** [comment]
Has updated in dev branch

**Comment by ShawLen** [comment]
Has updated in dev branch.
